### ISSUE TITLE
Chrome to drop HTTP-Based Public Key Pinning

### ISSUE THREAD

**Issue by nikwen** [helmetjs/hpkp#14]
Chrome is about to drop support for HTTP-Based Public Key Pinning.

https://developers.google.com/web/updates/2018/04/chrome-67-deps-rems

**Comment by EvanHahn** [comment]
Interesting. Do you know if other browsers intend to follow suit?

**Comment by nikwen** [comment]
I don't have any information on what other browsers will do.

**Comment by EvanHahn** [comment]
My plan here is:

1. Add some notes about this in the documentation (already done)
2. Wait until Chrome 69 comes out
3. If they change their minds and _don't_ remove it, update the documentation but leave the warnings
4. Remove this from Helmet version 4 (but don't completely deprecate this module)

**Comment by EvanHahn** [comment]
Chrome 69 doesn't appear to be out yet. I'll check back in sometime in October.

**Comment by egorFiNE** [comment]
:point_up:

**Comment by EvanHahn** [comment]
I'll take a look at this.

**Comment by EvanHahn** [comment]
Hmm, I didn't see anything in any release notes about this. Anybody know where a HPKP is explicitly removed from Chrome?

**Comment by EvanHahn** [comment]
Never mind. Just saw the message in the Chrome console for myself.

I've updated the readme and docs on helmetjs.github.io.

I've created https://github.com/helmetjs/helmet/issues/180 to track the removal of this middleware from "mainline" Helmet. I'm going to close this issue for now because there's not more to do in this repository.

Thanks for your help, everyone!
